### ISSUE TITLE
功能改进建议

### ISSUE THREAD

**Issue by 1103859909** [erzaozi/imgS-plugin#2]
没有相似度功能的搜索引擎在搜索图片是他会把搜索到的图片发出来就会导致其他的搜索引擎不能继续搜索下去，就只能搜索一个一个选择搜索引擎了，如图所示。
![{CF0705D7-D732-41dc-B681-946789D274EE}](https://github.com/erzaozi/imgS-plugin/assets/107859647/4810c202-c115-4f7f-a65d-1892f7dfbb8f)
![{B9F433CE-76A9-45e6-9831-F4578A2FF7B6}](https://github.com/erzaozi/imgS-plugin/assets/107859647/83b42581-f5a8-46d1-bf99-acf1b88b57e1)
所以我的想法是能不能无论是否搜索到都把所以的已选择的搜索引擎全部搜索一边，在一次性的发出来，另外自动切换引擎的信息也挺刷屏的

**Comment by 1103859909** [comment]
还有我发现只要聊天中包含搜图两个字的句子就会触发搜索
-![32cec12860c7b4a7e1c9c85964422e9d](https://github.com/erzaozi/imgS-plugin/assets/107859647/dbaf5ed5-f146-4a43-8547-48968436ac20)

**Comment by CikeyQi** [comment]
首先，非常感谢您提出的几点建议，以下是处理结果：
- 关于你提到的 **把已选择的搜索引擎全部搜索一遍** 的建议可能会导致搜索等待时间过长的问题，所以我认为这不是一个好的解决方法，所以暂不采纳
- 关于你提到 **自动切换引擎信息刷屏** 的问题将会在后续更新提供开关，且默认为关闭
- 关于你提到 **包含搜图两个字就会触发搜索** 的问题将会在后续更新中解决
