### ISSUE TITLE
结果的缩略图过期

### ISSUE THREAD

**Issue by xingyu42** [erzaozi/imgS-plugin#3]
## 挂了代理的，还是出现过期问题
![image](https://github.com/erzaozi/imgS-plugin/assets/52421598/8d55398e-4e63-47d0-8883-9d393533c962)

**Comment by CikeyQi** [comment]
发送图片 `segment.image()` 方法不走代理

**Comment by xingyu42** [comment]
这样啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月8日(周六) 凌晨1:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [erzaozi/imgS-plugin] 结果的缩略图过期 (Issue #3)




 
发送图片 segment.image() 方法不走代理

**Comment by devil233-ui** [comment]
> 发送图片 `segment.image()` 方法不走代理

为什么我海外服务器也会过期，报的是403来着
![Image_1731523740543](https://github.com/user-attachments/assets/5c8b0c7b-dcf2-4a98-a37b-c21a42147654)
代理开关是关闭的

**Comment by devil233-ui** [comment]
大佬看下这个 #https://github.com/zhiyu1998/rconsole-plugin/pull/55 这边会不会也能这么解决呢？目前来看只要改ac的缩略图就行<img width="1022" alt="5dc2491530494b67fb130bd41a6eab3" src="https://github.com/user-attachments/assets/700c2bfe-2d44-4eb3-9704-724a097412ca">

试了下lgl更惨
<img width="409" alt="b93b350980e8b2dc56f18a4d70f9726" src="https://github.com/user-attachments/assets/5a469603-c773-4263-97c6-61fa3b5d2f8c">
<img width="919" alt="7f0542c38dbe061d2a695085e363cd4" src="https://github.com/user-attachments/assets/6975a2e5-af35-4803-8b32-994f27538ebc">
