### ISSUE TITLE
收不到待搜索图片

### ISSUE THREAD

**Issue by half-drop** [erzaozi/imgS-plugin#4]
之前还好好的，这两天出现的问题

[MiaoYz][10:29:51.036][INFO] [imgS-以图搜源][search][测试消息(‍)] /搜图
[MiaoYz][10:29:51.658][INFO] succeed to send: [Group(776962739)] 请发送你要搜索
的图片
[MiaoYz][10:29:51.661][MARK] [imgS-以图搜源][search] /搜图 处理完成 625ms
[MiaoYz][10:29:54.938][INFO] recv from: [Group: 测试消息(776962739), Member: ‍(
1097982745)] {image:AC0675D6D2F3469C593136E7DB09610A}
[MiaoYz][10:29:55.381][INFO] succeed to send: [Group(776962739)] 正在使用 Sauce
NAO 搜索引擎搜索图片，请稍等...
[MiaoYz][10:29:58.893][ERRO] 下载待搜索图片失败 FetchError: request to https://
multimedia.nt.qq.com.cn&rkey=caiskksbekjvg1fmcydbh-sqgznz5rjjylruxxfbfl8yc-g23v
qjnn8jkyg&spec=0/ failed, reason: getaddrinfo ENOTFOUND multimedia.nt.qq.com.cn
&rkey=caiskksbekjvg1fmcydbh-sqgznz5rjjylruxxfbfl8yc-g23vqjnn8jkyg&spec=0
    at ClientRequest.<anonymous> (file:///C:/Users/Administrator/Desktop/Yunzai
/Miao-Yunzai/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/in
dex.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:
21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  erroredSysCall: 'getaddrinfo'
}
[MiaoYz][10:29:58.897][ERRO] [Ascii2d] 返回错误：TypeError [ERR_INVALID_ARG_TYP
E]: The "path" argument must be of type string or an instance of Buffer or URL.
 Received null
[MiaoYz][10:29:59.328][INFO] succeed to send: [Group(776962739)] 已使用 SauceNA
O/IqDB/Yandex/Ascii2d 搜索引擎搜索图片，未找到相关图片，换个搜索引擎试试吧？

**Comment by CikeyQi** [comment]
日志中有 `下载待搜索图片失败` 字样，判断为收到的图片链接无法解析，疑似 `rkey` 问题，这属于协议端问题，与本插件无关，建议更新协议端或向协议端反馈
